import jinja2
# import sys
import os
import argparse
from parse import parse, escape
from model import ParamTable


# sys.path.append(os.path.join(os.environ['COPPELIASIM_ROOT_DIR'],
#                              "programming/libPlugin/simStubsGen"))

def generate_markdown_api(directory, file):
    plugin = parse(os.path.join(directory, file))
    templateLoader = jinja2.FileSystemLoader(searchpath=os.path.dirname(__file__))
    env = jinja2.Environment(loader=templateLoader)
    template = env.get_template("api.md.j2")
    r = template.render(plugin=plugin)
    with open(os.path.join(directory, f'api_{plugin.name}.md'), 'w') as f:
        f.write(r)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate API docs in markdown')
    parser.add_argument('--directory', type=str, default=".",
                        help='the directory with the autogenerated files')
    parser.add_argument('--file', type=str, default="reference.xml",
                        help='the reference xml file')
    args = parser.parse_args()
    generate_markdown_api(args.directory, args.file)
