import argparse
from generate_split_reference import generate_split_reference
from generate_markdown_api import generate_markdown_api
from generate_lua import generate_lua
# import xml.etree.ElementTree as ET


def main(directory):
    source = 'reference.xml'
    thymio = 'reference_Thymio.xml'
    aseba, thymio = generate_split_reference(directory, source)
    # does not work as they are not cleaning ET so a subsequent parsing will fail
    generate_markdown_api(directory, aseba)
    generate_markdown_api(directory, thymio)
    generate_lua(directory, source)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate simplier Thymio2 interface')
    parser.add_argument('--directory', type=str, default=".",
                        help='the directory witht the autogenerated files')
    args = parser.parse_args()
    main(args.directory)
